### PR TITLE
Get it building on ghc 8.6

### PR DESCRIPTION
**Pull request by isovector**
I needed this library for my work on isovector/algebra-checkers. It needed a tiny little TLC to get compiling on 8.6. Not sure what the state of this project is, but I'm happy to take up maintenance if you are too busy!

### CODE REVIEW

**Review by nikita-volkov — CHANGES_REQUESTED** [review]
I would confirm this PR if not for a few problems.

1. I disagree with the introduction of Stack. Stack is a good tool when you need a reproducible build with a specific tree of dependencies (e.g., in application development). It is not a proper tool for libraries with ranges of supported dependencies. So please either use Cabal for building or at least don't commit Stack files into the repo.

    In case you choose to keep working with Stack, you can list the Stack files in your own .gitignore, so that Git doesn't try to add Stack files in your each commit, e.g.:
    ```gitignore
    /.gitignore
    /stack.yaml
    /stack.yaml.lock
    ```

     I intentionally never include .gitignore in the repos, so that each developer can have his own version of it.

2. I disagree with removal of version ranges of the dependencies. Thus you've virtually eliminated all compatibility assurances of the library. So please reintroduce version ranges, updating them in accordance. I've already checked the changes regarding TH, its version range should be the following:

    ```cabal
    template-haskell >=2.11 && <2.16
    ```
3. The CI build fails since the .travis file was not updated according to the introduced changes. Please correct the list of supported GHCs thru the environment vars there.

**Comment by isovector** [comment]
I'm going to leave this PR in your capable hands; feel free to make whatever changes necessary to get it merge-ready. Thanks!

**Comment by nikita-volkov** [comment]
I've updated the package sidestepping this PR and released it as 0.1.5.

**Comment by isovector** [comment]
Thanks!

**Pull request closed without merging**
